//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningScheduleBokkingManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingScheduleManagementSystemEntities2 : DbContext
    {
        public BookingScheduleManagementSystemEntities2()
            : base("name=BookingScheduleManagementSystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BUILDING> BUILDINGS { get; set; }
        public virtual DbSet<CLEANING_AREA> CLEANING_AREA { get; set; }
        public virtual DbSet<CleaningSchedule> CleaningSchedules { get; set; }
        public virtual DbSet<FLOOR> FLOORS { get; set; }
        public virtual DbSet<GROUP> GROUPS { get; set; }
        public virtual DbSet<RESIDENT> RESIDENTS { get; set; }
        public virtual DbSet<ROOM> ROOMS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
