//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningScheduleBokkingManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESIDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESIDENT()
        {
            this.CLEANINGSCHEDULEs = new HashSet<CLEANINGSCHEDULE>();
        }
    
        public int Resident_Id { get; set; }
        public string Full_Name { get; set; }
        public int Contact_No { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Group_Id { get; set; }
        public bool Is_Admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLEANINGSCHEDULE> CLEANINGSCHEDULEs { get; set; }
        public virtual GROUP GROUP { get; set; }
    }
}
