//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningScheduleBokkingManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public int Room_Id { get; set; }
        public string Room_Name { get; set; }
        public int Group_Id { get; set; }
        public int Floor_Id { get; set; }
    
        public virtual FLOOR FLOOR { get; set; }
        public virtual GROUP GROUP { get; set; }
    }
}
